config/routes.rb
Rails.application.routes.draw do
  root to: "application#index"
  
  resources :products, only: [:index]
  resources :available_products, only: [:index, :new, :create, :destroy] do
    member do 
      post :add_quantity
      post :remove_quantity
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/available_product.rb
class AvailableProduct < ApplicationRecord
  belongs_to :product
  belongs_to :color
  belongs_to :size

  accepts_nested_attributes_for :product, update_only: true

  validates :color_id, :size_id, presence: true
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :available_products
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :available_products
  validates :name, :description, presence: true
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :available_products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    redirect_to available_products_path
  end
end

app/controllers/available_products_controller.rb
class AvailableProductsController < ApplicationController

  def index
    @available_products = AvailableProduct.all
  end

  def create
    AvailableProduct.transaction do
      begin
        if available_product_params[:product_id].blank?
          product = Product.create!(product_params)
          AvailableProduct.create!(available_product_params.merge(product_id: product.id))
        else
          AvailableProduct.find_or_initialize_by(
            product_id: available_product_params[:product_id],
            color_id: available_product_params[:color_id],
            size_id: available_product_params[:size_id]).tap do |available_product|
            available_product.quantity = available_product.quantity + available_product_params[:quantity].to_i
            available_product.save!
          end
        end

        redirect_to available_products_path, notice: 'Cadastro realizado com sucesso'
      rescue
        redirect_to available_products_path, notice: 'Ocorreu algo de errado, tente novamente'
      end
    end
  end

  def new
    @available_product = AvailableProduct.new
    @available_product.build_product

    @colors = Color.all
    @sizes = Size.all
  end

  def add_quantity
    available_product = AvailableProduct.find(params[:id])
    available_product.update_attributes!(quantity: available_product.quantity + 1)
    render json: {}
  end

  def remove_quantity
    available_product = AvailableProduct.find(params[:id])
    available_product.update_attributes!(quantity: available_product.quantity - 1)
    render json: {}
  end

  private

  def available_product_params
    params
      .require(:available_product)
      .permit(:color_id, :size_id, :product_id, :quantity)
  end

  def product_params
    params
      .require(:available_product)
      .require(:product_attributes)
      .permit(:name, :description)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    render json: Product.all.as_json(only: [:id, :name, :description])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/available_products/index.html.erb
<table class="table table-hover table-sm table-bordered">
  <thead>
    <tr>
      <th class="align-middle text-center" scope="col">Nome</th>
      <th class="align-middle text-center" scope="col">Descrição</th>
      <th class="align-middle text-center" scope="col">Cor</th>
      <th class="align-middle text-center" scope="col">Tamanho</th>
      <th class="align-middle text-center" scope="col">Quantidade disponível</th>
      <th class="align-middle text-center" scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% for item in @available_products %>
      <tr>
        <td class="align-middle text-center"><%= item.product.name %></td>
        <td class="align-middle text-center"><%= item.product.description %></td>
        <td class="align-middle text-center"><%= item.color.name %></td>
        <td class="align-middle text-center"><%= item.size.name %></td>
        <td class="align-middle text-center"><span class="badge badge-primary badge-pill product_quantity"><%= item.quantity %></span></td>
        <td class="d-flex justify-content-center align-middle">
            <%= button_to "-", remove_quantity_available_product_path(item), remote: true, class: "btn btn-danger", form: { class: 'quantity_shift '} %>
            <%= button_to "+", add_quantity_available_product_path(item), remote: true, class: "btn btn-success", form: { class: 'quantity_plus '} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/available_products/new.html.erb
<%= simple_form_for @available_product do |f| %> 
  <%= f.hidden_field :product_id %>
    
  <%= f.simple_fields_for :product, @available_product.product do |product_form| %>
    <%= product_form.input :name, label: "Nome" %>
    <%= product_form.input :description, label: "Descrição" %>
  <% end %>

  <%= f.input :color_id, collection: @colors, label: "Cor" %>
  <%= f.input :size_id, as: :radio_buttons, collection: @sizes, label: "Tamanho" %>
  
  <%= f.input :quantity, label: "Quantidade", type: :number %>

  <%= f.button :submit, "Cadastrar" %>
  <button type="button" id="reset_form" class="btn btn-link">Limpar formulário</button>

<% end %>
<script type="text/javascript">
$(document).ready(function(){
  var products = [];

  $('#reset_form').on('click', reset_form);

  var new_product_form = $("#new_available_product").validate({
    rules: {
      'available_product[product_attributes][name]': {
        required: true,
        minlength: 2
      },
      'available_product[product_attributes][description]': {
        required: true,
        minlength: 6
      },
      'available_product[color_id]': {
        required: true,
      },
      'available_product[size_id]':{
        required: true,
      },
      'product_quantity':{
        required: true,
        min: 1,
      },
    },
    messages:{
      'available_product[product_attributes][name]': {
        required: "Favor preencher o Nome do produto",
        minlength: "Digite no minimo 2 caracteres"
      },
      'available_product[product_attributes][description]': {
        required: "Favor preencher o Nome do produto",
        minlength: "Digite no minimo 6 caracteres"
      },
      'available_product[color_id]': {
        required: "Escolha uma cor"
      },
      'available_product[size_id]': {
        required: "Escolha um Tamanho"
      },
      'product_quantity': {
        required: "Valor minimo 01"
      }
    },
    errorPlacement: function(error, element) {
      if ( element.is(":radio") ) {
        error.appendTo( element.parents('fieldset') );
      }
      else {
        error.insertAfter( element );
      }
    },
  });

  $.ajax({
    dataType: 'json',
    type: 'GET',
    url: '/products/',

    success: function(data) {
      products = data
    },
    error: function(data) {
      console.log('erro');
    }
  });

  $('#available_product_product_attributes_name').autocomplete({
    source: function (request, response) {
      response($.map(products, function (value, key) {
        return {
          label: value.name + " (" + value.description + ")",
          value: value.id,
          desc: value.description
        }
      }));
    },
    focus: function(event, ui) {
      event.preventDefault();
    },
    select: function(event, ui) {
      event.preventDefault();
      $('#available_product_product_attributes_name').val(ui.item.label);
      $('#available_product_product_attributes_name').prop('readonly', true);
      $('#available_product_product_attributes_description').val(ui.item.desc);
      $('#available_product_product_attributes_description').prop('readonly', true);
      $('#available_product_product_id').val(ui.item.value);
    },
  });

  function reset_form() {
    $('#available_product_product_attributes_name').val('').prop('readonly', false);
    $('#available_product_product_attributes_description').val('').prop('readonly', false);
    $('#product_available_products_attributes_0_color_id').val('');
    $('#available_product_quantity').val('1');
    new_product_form.resetForm();
  }
    
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SisSynergiaTesteRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.16.0/jquery.validate.min.js"></script>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">Synergia T-shirts</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="<%= available_products_path %>">Produtos</a>
        <a class="p-2 text-dark" href="<%= new_available_product_path %>">Cadastrar</a>
      </nav>
    </div> 
    <div class="container"> 
      <p id="notice"><%= notice %></p> 
      <%= yield %>
    </div>
    <script type="text/javascript">
      $(document).ready(function(){
        $('.quantity_plus').bind("ajax:success", function(data) {
          var $span = $(this).parent().parent().find('.product_quantity');
          var current_quantity = parseInt($span.text());
          $span.text(current_quantity + 1);
        });

        $('.quantity_shift').bind("ajax:success", function(data) {
          var $span = $(this).parent().parent().find('.product_quantity');
          var current_quantity = parseInt($span.text());
          $span.text(current_quantity - 1);
        });
      });
    </script>
  </body>
</html>